FROM compilers-rump-base-common

ENV PLATFORM=xen
ENV BUILDRUMP_EXTRA=

RUN cd /opt/rumprun && \
    ./build-rr.sh -d $DESTDIR -o ./obj $PLATFORM build -- $BUILDRUMP_EXTRA && \
    ./build-rr.sh -d $DESTDIR -o ./obj $PLATFORM install

COPY fixrump.sh /tmp
RUN bash -ex /tmp/fixrump.sh

VOLUME /opt/code
WORKDIR /opt/code


# RUN LIKE THIS: docker run --rm -v -ti /path/to/code:/opt/code compilers-rump-base-common-xen
