FROM ubuntu:14.04

RUN apt-get update -y  &&  apt-get install libxen-dev curl git build-essential -y &&  apt-get clean -y &&  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV RUMPDIR=/usr/local

RUN cd /opt && \
    git clone https://github.com/rumpkernel/rumprun
RUN cd /opt/rumprun && git checkout 2765be8808ad44bdb938582c6aa82d2a2676e1e4
RUN cd /opt/rumprun && git submodule update --init


VOLUME /opt/code
WORKDIR /opt/code
