FROM ubuntu:14.04

RUN apt-get update -y  &&  apt-get install libxen-dev curl git build-essential -y &&  apt-get clean -y &&  rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ENV DESTDIR=/usr/local

RUN cd /opt && \
    git clone --recursive https://github.com/rumpkernel/rumprun

VOLUME /opt/code
WORKDIR /opt/code
