FROM ubuntu:16.04
MAINTAINER includeos.org
RUN \
  apt-get update && \
  apt-get install -y bc git lsb-release sudo
RUN cd ~ && pwd && \
  git clone https://github.com/hioa-cs/IncludeOS.git && \
  cd IncludeOS && \
  git checkout 724f28ec31fa465c2eb9047c77f128d38baac5f0 && \
  git fetch --tags && \
  /bin/bash ./install.sh
